sudo: required

os: ubuntu

language: node_js
node_js:
  - "8.11.3"

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

cache:
  directories:
    "node_modules"

env:
  - MYSQL_DATABASE_NAME=enrollment_system
  - MYSQL_USERNAME=root
  - MYSQL_PASSWORD=root
  - NODE_ENV=testing
  - JWT_PASSWORD=ThisIsATest

before_install:
  - npm i -g npm@5.6.0
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='root';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
  - npm install
  - npm run build
script:
  - npm run test